version: 2
jobs:
  build_site:
    docker:
      - image: node:14.17.0

    working_directory: ~/personnal-site

    steps:
      - checkout

      #download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests
      - run: npm run build

      - run:
          name: Firebase Deploy
          command: firebase deploy --token "$FIREBASE_TOKEN"

version: 2.1
workflows:
  build_site:
    jobs:
      - build_site:
          filters:
            branches:
              only: develop